import 'package:flutter/cupertino.dart';
import 'dart:convert';
// ignore: implementation_imports
import 'package:google_fonts/src/google_fonts_base.dart' as fonts;
import 'dart:io';
import 'dart:ui' as ui;
import 'package:c_h_o_l_o_t_o_dashboard/flutter_flow/internationalization.dart';
import 'package:c_h_o_l_o_t_o_dashboard/flutter_flow/flutter_flow_widgets.dart';
import 'package:c_h_o_l_o_t_o_dashboard/payments/payment_request.dart';
import 'package:c_h_o_l_o_t_o_dashboard/payments/payment_reviews_widget.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_test/flutter_test.dart';

class TestLocaleDelegate extends LocalizationsDelegate<FFLocalizations> {
  const TestLocaleDelegate();
  @override
  bool isSupported(Locale locale) => true;
  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture(FFLocalizations(locale));
  @override
  bool shouldReload(TestLocaleDelegate old) => false;
}

class TestFontManifest extends Fake implements AssetManifest {
  @override
  List<String> listAssets() => [
        for (final family in ['Inter', 'InterTight'])
          for (final weight in [
            'Regular',
            'Medium',
            'SemiBold',
            'Bold',
            'ExtraBold'
          ])
            '$family-$weight.ttf'
      ];
}

class TestMaterialLocale extends LocalizationsDelegate<MaterialLocalizations> {
  const TestMaterialLocale();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'cr';
  @override
  Future<MaterialLocalizations> load(Locale locale) =>
      GlobalMaterialLocalizations.delegate.load(const Locale('fr'));
  @override
  bool shouldReload(TestMaterialLocale old) => false;
}

class TestCupertinoLocale
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const TestCupertinoLocale();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'cr';
  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      GlobalCupertinoLocalizations.delegate.load(const Locale('fr'));
  @override
  bool shouldReload(TestCupertinoLocale old) => false;
}

void main() {
  late Uint8List proof;
  TestWidgetsFlutterBinding.ensureInitialized();
  setUpAll(() async {
    if (const bool.fromEnvironment('CAPTURE_PAYMENT_UI')) {
      final icons = FontLoader('MaterialIcons')
        ..addFont(rootBundle.load('fonts/MaterialIcons-Regular.otf'));
      await icons.load();
      for (final entry in {
        'Inter': '/tmp/choloto-inter.ttf',
        'InterTight': '/tmp/choloto-inter-tight.ttf'
      }.entries) {
        final bytes =
            ByteData.sublistView(await File(entry.value).readAsBytes());
        for (final suffix in [
          '',
          '_regular',
          '_medium',
          '_semiBold',
          '_bold'
        ]) {
          final font = FontLoader('${entry.key}$suffix')
            ..addFont(Future.value(bytes));
          await font.load();
        }
      }
    }
  });
  setUpAll(() async {
    // A valid JPEG fixture is generated by the client conversion test when
    // capturing; a one-pixel PNG also exercises Flutter's preview in normal runs.
    if (!File('/tmp/choloto-test-receipt.jpg').existsSync()) {
      final recorder = ui.PictureRecorder();
      Canvas(recorder).drawRect(const Rect.fromLTWH(0, 0, 100, 100),
          Paint()..color = const Color(0xFFFFFFFF));
      final image = await recorder.endRecording().toImage(100, 100);
      final bytes = await image.toByteData(format: ui.ImageByteFormat.png);
      await File('/tmp/choloto-test-receipt.jpg')
          .writeAsBytes(bytes!.buffer.asUint8List());
      image.dispose();
    }
  });
  setUpAll(() async {
    fonts.assetManifest = TestFontManifest();
    const capture = bool.fromEnvironment('CAPTURE_PAYMENT_UI');
    final inter = capture
        ? ByteData.sublistView(
            await File('/tmp/choloto-inter.ttf').readAsBytes())
        : ByteData(0);
    final tight = capture
        ? ByteData.sublistView(
            await File('/tmp/choloto-inter-tight.ttf').readAsBytes())
        : ByteData(0);
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMessageHandler('flutter/assets', (message) async {
      final path = utf8.decode(message!.buffer.asUint8List());
      if (path.endsWith('.ttf')) {
        return path.startsWith('InterTight') ? tight : inter;
      }
      return null;
    });
    proof = await File('/tmp/choloto-test-receipt.jpg').readAsBytes();
  });
  final request = PaymentRequest('r1', {
    'user_uid': 'member-123',
    'status': 'pending',
    'note': 'Renouvellement VIP',
    'created_at': DateTime(2026, 9, 5)
  });
  Widget app(
          {String locale = 'fr',
          bool dark = false,
          bool missingProof = false,
          Future<String> Function(DateTime, double, String, String)?
              approve}) =>
      MaterialApp(
          locale: Locale(locale),
          supportedLocales: const [Locale('fr'), Locale('en'), Locale('cr')],
          localizationsDelegates: const [
            TestLocaleDelegate(),
            TestMaterialLocale(),
            TestCupertinoLocale(),
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            FallbackMaterialLocalizationDelegate(),
            FallbackCupertinoLocalizationDelegate()
          ],
          theme:
              ThemeData(brightness: dark ? Brightness.dark : Brightness.light),
          home: RepaintBoundary(
              key: const ValueKey('capture'),
              child: PaymentReviewPage(
                  request: request,
                  loadReview: () async => PaymentReviewData({
                        'display_name': 'Membre de démonstration',
                        'email': 'client@example.test',
                        'phone_number': '+509 0000 0000',
                        'end_sub': DateTime(2026, 9, 30)
                      }, missingProof ? null : proof),
                  approveReview:
                      approve ?? (_, __, ___, ____) async => 'proof_r1',
                  rejectReview: (_) async {})));
  for (final locale in ['fr', 'en', 'cr']) {
    for (final dark in [false, true]) {
      for (final width in [320.0, 1440.0]) {
        testWidgets('review $locale dark=$dark width=$width', (tester) async {
          tester.view.physicalSize = Size(width, 1000);
          tester.view.devicePixelRatio = 1;
          addTearDown(tester.view.resetPhysicalSize);
          addTearDown(tester.view.resetDevicePixelRatio);
          await tester.pumpWidget(app(locale: locale, dark: dark));
          await tester.runAsync(() async =>
              Future<void>.delayed(const Duration(milliseconds: 100)));
          await tester.pumpAndSettle();
          await tester.runAsync(() => precacheImage(MemoryImage(proof),
              tester.element(find.byType(PaymentReviewPage))));
          await tester.pumpAndSettle();
          expect(tester.takeException(), isNull);
          if (const bool.fromEnvironment('CAPTURE_PAYMENT_UI')) {
            await tester.runAsync(() async {
              final boundary = tester.renderObject<RenderRepaintBoundary>(
                  find.byKey(const ValueKey('capture')));
              final image = await boundary.toImage(pixelRatio: 1);
              final bytes =
                  await image.toByteData(format: ui.ImageByteFormat.png);
              await File(
                      '/tmp/choloto-review-$locale-$dark-${width.toInt()}.png')
                  .writeAsBytes(bytes!.buffer.asUint8List());
              image.dispose();
            });
          }
          await tester
              .ensureVisible(find.byKey(const ValueKey('rejection-reason')));
          await tester.pumpAndSettle();
          expect(tester.takeException(), isNull);
        });
      }
    }
  }
  testWidgets('missing proof disables approval', (tester) async {
    await tester.pumpWidget(app(missingProof: true));
    await tester.pumpAndSettle();
    final action = find.descendant(
        of: find.byKey(const ValueKey('approve-payment')),
        matching: find.byType(FFButtonWidget));
    expect(tester.widget<FFButtonWidget>(action).onPressed, isNull);
  });
  testWidgets('approval shows saved receipt and removes review actions',
      (tester) async {
    var calls = 0;
    await tester.pumpWidget(app(approve: (end, amount, currency, method) async {
      calls++;
      expect(amount, 2000.5);
      expect(currency, 'GDS');
      expect(method, 'moncash');
      return 'proof_r1';
    }));
    await tester.runAsync(
        () async => Future<void>.delayed(const Duration(milliseconds: 100)));
    await tester.pumpAndSettle();
    await tester.ensureVisible(find.byKey(const ValueKey('approve-payment')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const ValueKey('approve-payment')));
    await tester.pumpAndSettle();
    expect(calls, 0, reason: 'The administrator must record the amount');
    await tester.ensureVisible(find.byKey(const ValueKey('review-amount')));
    await tester.enterText(
        find.byKey(const ValueKey('review-amount')), '2000,50');
    await tester.ensureVisible(find.byKey(const ValueKey('approve-payment')));
    await tester.tap(find.byKey(const ValueKey('approve-payment')));
    await tester.pumpAndSettle();
    expect(calls, 1);
    expect(find.text('CH-proof_r1'), findsOneWidget);
    expect(find.byKey(const ValueKey('approve-payment')), findsNothing);
  });
}
